#!/bin/bash

az servicebus namespace authorization-rule create \
    --resource-group monsenso-$DEPL_REGION-$ENV-service-bus-rg \
    --namespace-name monsenso-$DEPL_REGION-$ENV-service-bus \
    --name serviceConnectionString \
    --rights Send > /dev/null

serviceBusConnectionString=$(
    az servicebus namespace authorization-rule keys list \
        --resource-group monsenso-$DEPL_REGION-$ENV-service-bus-rg \
        --namespace-name monsenso-$DEPL_REGION-$ENV-service-bus \
        --name serviceConnectionString \
    | jq -r .primaryConnectionString
)

echo $serviceBusConnectionString