#!/bin/bash

primarySharedKey=$(
    az monitor log-analytics workspace get-shared-keys \
        --resource-group monsenso-$DEPL_REGION-$ENV-monitoring-core-rg \
        --workspace-name monsenso-$SERVING_REGION-$ENV-ws \
    | jq -r .primarySharedKey
)

echo $primarySharedKey