#!/bin/bash

connectionString=$(
    az signalr key list \
        --resource-group monsenso-$DEPL_REGION-$ENV-signalr-rg \
        --name monsenso-$DEPL_REGION-$ENV-signalr \
    | jq -r .primaryConnectionString
)

echo $connectionString