#!/bin/bash

primarySharedKey=$(
    az monitor log-analytics workspace get-shared-keys \
        --resource-group monsenso-$DEPL_REGION-$ENV-log-analytics-rg \
        --workspace-name monsenso-$DEPL_REGION-$ENV-log-analytics \
    | jq -r .primarySharedKey
)

echo $primarySharedKey