#!/bin/bash

stty -echo
printf "URI to the Storage blob file containing data protection keys for the IdentityServers. "
printf "The file will be created by the service if it does not exist:"
read $URI
stty echo

echo $URI
