#!/bin/bash

echo "URI to the Storage blob file containing data protection keys for the IdentityServers. " >&2
echo "The file will be created by the service if it does not exist:" >&2
stty -echo
read $URI
stty echo

echo $URI
