#!/bin/bash

key=$(
    az functionapp keys list \
        --resource-group monsenso-$DEPL_REGION-$ENV-appservice-function-linux-rg \
        --name monsenso-aue-prd-system-functions \
    | jq .functionKeys.default
)
echo $key