#!/bin/bash

connectionString=$(
    az storage account show-connection-string \
        --resource-group monsenso-$DEPL_REGION-$ENV-appservice-function-linux-rg \
        --name monsenso${DEPL_REGION}${ENV}sysfunc01 \
    | jq -r .connectionString
)

echo $connectionString