#!/bin/bash

key=$(
    az functionapp keys list \
        --resource-group monsenso-$DEPL_REGION-$ENV-appservice-function-linux-rg \
        --name monsenso-$DEPL_REGION-$ENV-system-functions \
    | jq -r .functionKeys.default
)
echo $key
